---

codecov:
  notify:
    after_n_builds: 10  # Number of test matrix+lint jobs uploading coverage
    wait_for_ci: false

  require_ci_to_pass: false

  token: cdeeaf15-22fb-4b66-ad64-f65790bf450b  # repo-scoped

comment:
  require_changes: true

coverage:
  range: 100..100
  status:
    patch:
      default:
        target: 100%
        flags:
        - pytest
    project:
      default:
        target: 100%
      lib:
        flags:
        - pytest
        paths:
        - src/
        target: 100%
      tests:
        flags:
        - pytest
        paths:
        - tests/
        target: 100%
      typing:
        flags:
        - MyPy
        target: 100%

...
