---

codecov:
  notify:
    after_n_builds: 16  # Number of test matrix+lint jobs uploading coverage
    wait_for_ci: false

  require_ci_to_pass: false

  token: >-  # notsecret  # repo-scoped, upload-only, stability in fork PRs
    cdeeaf15-22fb-4b66-ad64-f65790bf450b

comment:
  require_changes: true

coverage:
  range: 60..90
  status:
    patch:
      default:
        target: 90%
      pytest:
        target: 90%
        flags:
        - pytest
    project:
      lib:
        flags:
        - pytest
        paths:
        - src/
        target: 56.10%
      tests:
        flags:
        - pytest
        paths:
        - tests/
        target: 90%

github_checks:
  annotations: false

...
